display error logs

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -46,7 +46,8 @@ jobs:
         echo "Environment variables:"
         env
         echo "Error Output:"
-        cat error.log
+        cat error.log || echo "error.log not found, displaying standard error instead:"
+        cat stderr.log
         coverage run manage.py test
 
 
